$ANSIBLE_VAULT;1.1;AES256
30383135326635623531613231336663306132326664636238636535343337636662653334366134
3835663839306539323531653438656531656438646537370a646231333062366666623762356631
30333830653730656234346436303032386239636431383663343664626231353033373064346436
3865303335663765360a656266643531393830333964313463333766303462383136643539383836
64393130323736353461343234313266313739643832373261303665663766376566313663626331
33313831383863373963613131616366623363376230653530313761336635656138346631383037
383033346165343835316364666335383366
