$ANSIBLE_VAULT;1.1;AES256
38663762343931373834356466646134353636386338333739343661346165316431646131363933
3233353136303064386564313464613861326564383762350a366639333134633963366132616434
63623437393034623536346262646466363237346534303362313964613234356565363036313539
6537656631306661640a343166636463623437393833346535643035623132663439656533653636
61343761633831386665336665613065316366626633353035323634336332653739633763633363
37666335336533633837383132313233346434396235626563353833613363303834616664313336
31383362303663626266656437636361373466363930336563646539356132343065663439343262
62646561633334646266633836393537343832656264343664373437383536366632353334373063
38643961396563643637313331366465396465323739316133366161336564383761356539393239
3636663835303737333365623661376637356538333064636634
